package net.c0f3.zookeeper;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.log4j.Logger;
import org.apache.zookeeper.inspector.logger.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;

public class ZKTreeExportDialogForm extends JDialog {
  private static Logger log = LoggerFactory.getLogger();

  private JPanel contentPane;
  private JButton buttonOK;
  private JButton buttonCancel;
  private JComboBox exportFormatSelector;
  private JProgressBar exportProgressBar;
  private JButton selectFolderButton;
  private JTextField destinationFolderPathTextField;
  private JLabel statusLabel;
  private final JFileChooser fc = new JFileChooser();
  // ----------------------------
  private final String connectString;
  private File choosenFile = null;

  public ZKTreeExportDialogForm(String connectString) {
    $$$setupUI$$$();
    this.connectString = connectString;
    setContentPane($$$getRootComponent$$$());
    setModal(true);
    getRootPane().setDefaultButton(buttonOK);

    buttonOK.addActionListener(e -> onOK());
    buttonCancel.addActionListener(e -> onCancel());

    // call onCancel() when cross is clicked
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        onCancel();
      }
    });

    // call onCancel() on ESCAPE
    contentPane.registerKeyboardAction(
        e -> onCancel(),
        KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
        JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
    );
    selectFolderButton.addActionListener(e -> {
      int returnVal = fc.showOpenDialog(ZKTreeExportDialogForm.this);
      if (returnVal == JFileChooser.APPROVE_OPTION) {
        choosenFile = fc.getSelectedFile();
        destinationFolderPathTextField.setText(choosenFile.getAbsolutePath());
        log.debug("Opening: " + choosenFile.getName());
      } else {
        log.debug("Open command cancelled by user.");
      }
    });
  }

  private void onOK() {
    if (exportFormatSelector.getSelectedItem() == null) {
      return;
    }
    String choosenExportFormat = exportFormatSelector.getSelectedItem().toString();
    if (choosenFile == null || choosenExportFormat == null) {
      statusLabel.setText("You have to choose destination file and export format");
      return;
    }
    this.setEnabled(false);
    ZKTreeExport treeExport = new ZKTreeExport(
        choosenExportFormat, choosenFile, connectString
    );
    treeExport.perform(this::dispose);
  }

  private void onCancel() {
    dispose();
  }

  public static void main(String[] args) {
    ZKTreeExportDialogForm dialog = new ZKTreeExportDialogForm("fedora-dev:2181");
    dialog.pack();
    dialog.setVisible(true);
    System.exit(0);
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPane = new JPanel();
    contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
    panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    buttonOK = new JButton();
    buttonOK.setText("OK");
    panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    buttonCancel = new JButton();
    buttonCancel.setText("Cancel");
    panel2.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    exportProgressBar = new JProgressBar();
    panel1.add(exportProgressBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
    contentPane.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    exportFormatSelector = new JComboBox();
    exportFormatSelector.setMaximumRowCount(3);
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    defaultComboBoxModel1.addElement(".zk");
    defaultComboBoxModel1.addElement("XML");
    defaultComboBoxModel1.addElement("folder");
    exportFormatSelector.setModel(defaultComboBoxModel1);
    exportFormatSelector.setToolTipText("zookeeper export format");
    panel3.add(exportFormatSelector, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    selectFolderButton = new JButton();
    selectFolderButton.setText("Select file");
    panel3.add(selectFolderButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    destinationFolderPathTextField = new JTextField();
    destinationFolderPathTextField.setEditable(false);
    destinationFolderPathTextField.setEnabled(true);
    panel3.add(destinationFolderPathTextField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    statusLabel = new JLabel();
    statusLabel.setText("");
    panel3.add(statusLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() { return contentPane; }

}
